import Home from "./home"
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Header from "../components/layout/Header";
import Footer from "@/components/layout/Footer";
import { useState } from "react";
import { useEffect } from "react";
import ProgressBar from "@/components/progress/ProgressBar";


const inter = Inter({ subsets: ['latin'] })

export default function Index() {

  return (
    <div>


      <div>
        <Head>
          <title>Create Next App</title>
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProgressBar />
        <Home />
      </div>

    </div>
  );
}